[package]
name = "rudis-server"
version = "0.0.1"
authors = ["Jmys"]
edition = "2021"


[dependencies]
anyhow = "1.0.59"                                   
bytes = "1.3.0"                                     
thiserror = "1.0.32"                               
tokio = { version = "1.23.0", features = ["full"] }
indicatif = "0.15.0"
regex = "1"
env_logger = "0.8"
log = "0.4"
redis = "0.21.4"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }