[package]
name = "rudis-server"
version = "0.0.6"
authors = ["就眠儀式"]
edition = "2024"

[dependencies]            
bytes = "1.3.0"
env_logger = "0.8"
anyhow = "1.0.59"
clap = { version = "4.2.1", features = ["derive"] }
tokio = { version = "1.41.1", features = ["full"] }
redis = "0.21.4"
log = "0.4"